server:
    port: 7777

spring:
    application:
        name: service1
eureka:
    client:    
        service-url:
            default-zone: http://localhost:8761/eureka/
instance:
    hostname: localhost